//! Writes crates/raam-core/src/palette.rs: both themes' M3 schemes baked
//! as constants, derived once here from the seed so `material-colors`
//! (HCT tonal palettes, TonalSpot: the Android default) never enters a
//! product build. Run `cargo run -p raam-palette` after changing a seed;
//! the test below fails CI whenever the checked-in table and this
//! derivation disagree.

use material_colors::color::Argb;
use material_colors::scheme::Scheme;
use material_colors::theme::{ColorGroup, CustomColor, ThemeBuilder};

/// Muted teal: calm next to photos, and far from skin tones.
const SEED: u32 = 0xff3f7a74;
/// Amber for "needs attention" notes (a missing album). M3 has no warning
/// role, so it's an M3 custom colour, harmonised towards the seed.
const WARNING_SEED: u32 = 0xffe0a100;

fn generate() -> String {
    let t = ThemeBuilder::with_source(Argb::from_u32(SEED))
        .custom_colors(vec![CustomColor {
            value: Argb::from_u32(WARNING_SEED),
            name: "warning".into(),
            blend: true,
        }])
        .build();
    let warn = &t.custom_colors[0];
    let mut out = String::from(
        "//! The baked M3 colour table: both themes' schemes, generated by\n\
         //! tools/palette from seed #3F7A74 (TonalSpot) with the amber warning\n\
         //! custom colour (#E0A100, harmonised towards the seed). Do not edit\n\
         //! by hand: run `cargo run -p raam-palette` after changing a seed\n\
         //! there; its test keeps this file and the derivation in step.\n\
         use crate::theme::Scheme;\n\
         use egui::Color32;\n\
         \n\
         const fn c(rgb: u32) -> Color32 {\n\
         \x20   let [_, r, g, b] = rgb.to_be_bytes();\n\
         \x20   Color32::from_rgb(r, g, b)\n\
         }\n",
    );
    for (name, scheme, group, dark) in [
        ("LIGHT", &t.schemes.light, &warn.light, false),
        ("DARK", &t.schemes.dark, &warn.dark, true),
    ] {
        out.push_str(&format!("\npub const {name}: Scheme = Scheme {{\n"));
        out.push_str(&format!("    dark: {dark},\n"));
        for (field, argb) in fields(scheme, group) {
            out.push_str(&format!(
                "    {field}: c(0x{:02x}{:02x}{:02x}),\n",
                argb.red, argb.green, argb.blue
            ));
        }
        out.push_str("};\n");
    }
    out
}

/// Every `Scheme` colour field, in the struct's declared order.
fn fields(s: &Scheme, w: &ColorGroup) -> Vec<(&'static str, Argb)> {
    vec![
        ("primary", s.primary),
        ("on_primary", s.on_primary),
        ("primary_container", s.primary_container),
        ("on_primary_container", s.on_primary_container),
        ("secondary", s.secondary),
        ("on_secondary", s.on_secondary),
        ("secondary_container", s.secondary_container),
        ("on_secondary_container", s.on_secondary_container),
        ("secondary_fixed_dim", s.secondary_fixed_dim),
        ("on_secondary_fixed", s.on_secondary_fixed),
        ("tertiary", s.tertiary),
        ("on_tertiary", s.on_tertiary),
        ("tertiary_container", s.tertiary_container),
        ("on_tertiary_container", s.on_tertiary_container),
        ("error", s.error),
        ("on_error", s.on_error),
        ("error_container", s.error_container),
        ("on_error_container", s.on_error_container),
        ("warning", w.color),
        ("on_warning", w.on_color),
        ("warning_container", w.color_container),
        ("on_warning_container", w.on_color_container),
        ("surface", s.surface),
        ("surface_dim", s.surface_dim),
        ("surface_bright", s.surface_bright),
        ("surface_container_lowest", s.surface_container_lowest),
        ("surface_container_low", s.surface_container_low),
        ("surface_container", s.surface_container),
        ("surface_container_high", s.surface_container_high),
        ("surface_container_highest", s.surface_container_highest),
        ("on_surface", s.on_surface),
        ("on_surface_variant", s.on_surface_variant),
        ("outline", s.outline),
        ("outline_variant", s.outline_variant),
        ("inverse_surface", s.inverse_surface),
        ("inverse_on_surface", s.inverse_on_surface),
        ("inverse_primary", s.inverse_primary),
        ("scrim", s.scrim),
        ("shadow", s.shadow),
    ]
}

fn main() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/raam-core/src/palette.rs"
    );
    std::fs::write(path, generate()).unwrap();
    println!("wrote {path}");
}

#[cfg(test)]
mod tests {
    /// The checked-in table is exactly this derivation (the register row's
    /// promise for the baked palette).
    #[test]
    fn baked_matches_derivation() {
        assert_eq!(
            include_str!("../../../crates/raam-core/src/palette.rs"),
            super::generate()
        );
    }
}
