//! Material Symbols Rounded codepoints for the icons in assets/icons.txt.
//! Generated by tools/build-icons.sh; do not edit by hand.
pub const SETTINGS: char = '\u{e8b8}';
pub const CLOSE: char = '\u{e5cd}';
pub const ARROW_BACK: char = '\u{e5c4}';
pub const CHEVRON_RIGHT: char = '\u{e5cc}';
pub const CHECK: char = '\u{e668}';
pub const ADD: char = '\u{e145}';
pub const REMOVE: char = '\u{e15b}';
pub const SEARCH: char = '\u{ef7a}';
pub const REFRESH: char = '\u{e5d5}';
pub const MORE_VERT: char = '\u{e5d4}';
pub const PLAY_ARROW: char = '\u{e037}';
pub const PAUSE: char = '\u{e034}';
pub const SKIP_NEXT: char = '\u{e044}';
pub const SKIP_PREVIOUS: char = '\u{e045}';
pub const PHOTO_LIBRARY: char = '\u{e413}';
pub const PHOTO_ALBUM: char = '\u{e411}';
pub const COLLECTIONS: char = '\u{e3d3}';
pub const IMAGE: char = '\u{e3f4}';
pub const FOLDER: char = '\u{e2c7}';
pub const CLOUD: char = '\u{f15c}';
pub const CLOUD_OFF: char = '\u{e2c1}';
pub const CLOUD_SYNC: char = '\u{eb5a}';
pub const DNS: char = '\u{e875}';
pub const KEY: char = '\u{e73c}';
pub const LINK: char = '\u{e250}';
pub const WIFI: char = '\u{e63e}';
pub const WIFI_OFF: char = '\u{e648}';
pub const SCHEDULE: char = '\u{efd6}';
pub const BEDTIME: char = '\u{f159}';
pub const LIGHT_MODE: char = '\u{e518}';
pub const DARK_MODE: char = '\u{e51c}';
pub const BRIGHTNESS_6: char = '\u{e3ab}';
pub const PALETTE: char = '\u{e40a}';
pub const FORMAT_SIZE: char = '\u{e245}';
pub const SLIDESHOW: char = '\u{e41b}';
pub const ANIMATION: char = '\u{e71c}';
pub const TIMER: char = '\u{e425}';
pub const TRANSITION_FADE: char = '\u{f50c}';
pub const WALLPAPER: char = '\u{e1bc}';
pub const CROP: char = '\u{e3be}';
pub const ASPECT_RATIO: char = '\u{e85b}';
pub const VISIBILITY: char = '\u{e8f4}';
pub const VISIBILITY_OFF: char = '\u{e8f5}';
pub const DELETE: char = '\u{e92e}';
pub const INFO: char = '\u{e88e}';
pub const WARNING: char = '\u{f083}';
pub const ERROR: char = '\u{f8b6}';
pub const CHECK_CIRCLE: char = '\u{f0be}';
pub const DOWNLOAD: char = '\u{f090}';
pub const UPLOAD: char = '\u{f09b}';
pub const LANGUAGE: char = '\u{ea07}';
pub const THERMOSTAT: char = '\u{f076}';
pub const LOCATION_ON: char = '\u{f1db}';
pub const CALENDAR_TODAY: char = '\u{e935}';
pub const TOUCH_APP: char = '\u{e913}';
pub const RESTART_ALT: char = '\u{f053}';
pub const TUNE: char = '\u{e429}';
pub const HISTORY: char = '\u{e8b3}';
pub const FAVORITE: char = '\u{e87e}';
pub const SYNC: char = '\u{e627}';
pub const UNDO: char = '\u{e166}';
pub const FIT_SCREEN: char = '\u{ea10}';
pub const DISPLAY_SETTINGS: char = '\u{eb97}';
pub const PAN_ZOOM: char = '\u{f655}';
pub const AUTO_AWESOME_MOSAIC: char = '\u{e660}';
pub const FORMAT_COLOR_FILL: char = '\u{e23a}';
pub const BACKSPACE: char = '\u{e14a}';
pub const SHIFT: char = '\u{e5f2}';
pub const FILE_EXPORT: char = '\u{f3b2}';
pub const CONTRAST: char = '\u{eb37}';
pub const SD_CARD: char = '\u{e623}';
pub const MOVIE: char = '\u{e404}';
pub const VOLUME_UP: char = '\u{e050}';
pub const AV_TIMER: char = '\u{e01b}';

/// Every icon above with its name, for the gallery.
pub const ALL: &[(&str, char)] = &[
    ("settings", SETTINGS),
    ("close", CLOSE),
    ("arrow_back", ARROW_BACK),
    ("chevron_right", CHEVRON_RIGHT),
    ("check", CHECK),
    ("add", ADD),
    ("remove", REMOVE),
    ("search", SEARCH),
    ("refresh", REFRESH),
    ("more_vert", MORE_VERT),
    ("play_arrow", PLAY_ARROW),
    ("pause", PAUSE),
    ("skip_next", SKIP_NEXT),
    ("skip_previous", SKIP_PREVIOUS),
    ("photo_library", PHOTO_LIBRARY),
    ("photo_album", PHOTO_ALBUM),
    ("collections", COLLECTIONS),
    ("image", IMAGE),
    ("folder", FOLDER),
    ("cloud", CLOUD),
    ("cloud_off", CLOUD_OFF),
    ("cloud_sync", CLOUD_SYNC),
    ("dns", DNS),
    ("key", KEY),
    ("link", LINK),
    ("wifi", WIFI),
    ("wifi_off", WIFI_OFF),
    ("schedule", SCHEDULE),
    ("bedtime", BEDTIME),
    ("light_mode", LIGHT_MODE),
    ("dark_mode", DARK_MODE),
    ("brightness_6", BRIGHTNESS_6),
    ("palette", PALETTE),
    ("format_size", FORMAT_SIZE),
    ("slideshow", SLIDESHOW),
    ("animation", ANIMATION),
    ("timer", TIMER),
    ("transition_fade", TRANSITION_FADE),
    ("wallpaper", WALLPAPER),
    ("crop", CROP),
    ("aspect_ratio", ASPECT_RATIO),
    ("visibility", VISIBILITY),
    ("visibility_off", VISIBILITY_OFF),
    ("delete", DELETE),
    ("info", INFO),
    ("warning", WARNING),
    ("error", ERROR),
    ("check_circle", CHECK_CIRCLE),
    ("download", DOWNLOAD),
    ("upload", UPLOAD),
    ("language", LANGUAGE),
    ("thermostat", THERMOSTAT),
    ("location_on", LOCATION_ON),
    ("calendar_today", CALENDAR_TODAY),
    ("touch_app", TOUCH_APP),
    ("restart_alt", RESTART_ALT),
    ("tune", TUNE),
    ("history", HISTORY),
    ("favorite", FAVORITE),
    ("sync", SYNC),
    ("undo", UNDO),
    ("fit_screen", FIT_SCREEN),
    ("display_settings", DISPLAY_SETTINGS),
    ("pan_zoom", PAN_ZOOM),
    ("auto_awesome_mosaic", AUTO_AWESOME_MOSAIC),
    ("format_color_fill", FORMAT_COLOR_FILL),
    ("backspace", BACKSPACE),
    ("shift", SHIFT),
    ("file_export", FILE_EXPORT),
    ("contrast", CONTRAST),
    ("sd_card", SD_CARD),
    ("movie", MOVIE),
    ("volume_up", VOLUME_UP),
    ("av_timer", AV_TIMER),
];
