//! The design system, layer 1 and 2: Material 3 tokens, and one function
//! that writes them into egui's own `Style`/`Visuals` for both themes.
//!
//! Nothing here knows about a host or GL. Widgets never hold colours of
//! their own: they ask `scheme(ui)`, which follows whichever theme egui is
//! drawing with, so a theme switch is `ctx.set_theme(..)` and nothing else.
//! The colours themselves are the baked table in palette.rs (generated by
//! tools/palette), so the derivation never runs on a frame.
//!
//! Sizes are M3's dp values used as egui points. At the frame's 160 dpi one
//! dp is one pixel, and `pixels_per_point` stays available as a single
//! global scale knob.
//!
//! Tokens are a vocabulary: some aren't used by the product yet.
#![allow(dead_code)]
use crate::{num, palette};
use egui::epaint::FontColorTransferFunction;
use egui::epaint::text::TextOptions;
use egui::style::{HandleShape, Selection, TextCursorStyle, WidgetVisuals, Widgets};
use egui::{
    Color32, Context, CornerRadius, FontData, FontDefinitions, FontFamily, FontId, Margin,
    RichText, Shadow, Stroke, Style, TextStyle, Theme, Ui, vec2,
};
use std::sync::{Arc, LazyLock};

// ---------------------------------------------------------------------------
// Colour: M3 roles from the baked table (tools/palette derives them from
// one seed with material-colors: HCT tonal palettes, TonalSpot variant).
// ---------------------------------------------------------------------------

/// Every M3 colour role this app uses, for one theme. `Copy` so a widget
/// can take its own copy per frame without borrowing egui's memory.
#[derive(Clone, Copy, Debug)]
pub struct Scheme {
    pub dark: bool,
    pub primary: Color32,
    pub on_primary: Color32,
    pub primary_container: Color32,
    pub on_primary_container: Color32,
    pub secondary: Color32,
    pub on_secondary: Color32,
    pub secondary_container: Color32,
    pub on_secondary_container: Color32,
    /// M3's fixed secondary roles (the same in both themes): the keyboard's
    /// function keys in the light theme, where secondary-container is the
    /// keyboard's own tone.
    pub secondary_fixed_dim: Color32,
    pub on_secondary_fixed: Color32,
    pub tertiary: Color32,
    pub on_tertiary: Color32,
    pub tertiary_container: Color32,
    pub on_tertiary_container: Color32,
    pub error: Color32,
    pub on_error: Color32,
    pub error_container: Color32,
    pub on_error_container: Color32,
    pub warning: Color32,
    pub on_warning: Color32,
    pub warning_container: Color32,
    pub on_warning_container: Color32,
    pub surface: Color32,
    pub surface_dim: Color32,
    pub surface_bright: Color32,
    pub surface_container_lowest: Color32,
    pub surface_container_low: Color32,
    pub surface_container: Color32,
    pub surface_container_high: Color32,
    pub surface_container_highest: Color32,
    pub on_surface: Color32,
    pub on_surface_variant: Color32,
    pub outline: Color32,
    pub outline_variant: Color32,
    pub inverse_surface: Color32,
    pub inverse_on_surface: Color32,
    pub inverse_primary: Color32,
    pub scrim: Color32,
    pub shadow: Color32,
}

/// Both themes' schemes, as stored in egui's memory.
#[derive(Clone, Copy, Debug)]
pub struct Schemes {
    pub light: Scheme,
    pub dark: Scheme,
}

impl Schemes {
    /// The baked table (see palette.rs for the seeds).
    pub fn baked() -> Self {
        Self {
            light: palette::LIGHT,
            dark: palette::DARK,
        }
    }

    pub fn get(&self, theme: Theme) -> &Scheme {
        match theme {
            Theme::Dark => &self.dark,
            Theme::Light => &self.light,
        }
    }
}

fn schemes_id() -> egui::Id {
    egui::Id::new("theme.schemes")
}

/// The scheme egui is currently drawing with.
///
/// # Panics
/// If `install` hasn't been called on this context.
pub fn scheme(ui: &Ui) -> Scheme {
    let dark = ui.visuals().dark_mode;
    let s = ui
        .ctx()
        .data(|d| d.get_temp::<Schemes>(schemes_id()))
        .expect("theme::install not called");
    if dark { s.dark } else { s.light }
}

/// The scheme for the theme egui draws with, from a Context (for Areas and
/// Modals, which have no Ui yet).
///
/// # Panics
/// If `install` hasn't been called on this context.
pub fn scheme_of(ctx: &egui::Context) -> Scheme {
    let s = ctx.data(|d| d.get_temp::<Schemes>(schemes_id()));
    s.map(|s| *s.get(ctx.theme()))
        .expect("theme::install not called")
}

/// M3 state layer: `on` drawn over `base` at `opacity`, precomputed because
/// egui has no overlay concept of its own (one fill per widget state).
pub fn layer(base: Color32, on: Color32, opacity: f32) -> Color32 {
    let mix = |b: u8, o: u8| {
        num::sat_u8((f32::from(b) + (f32::from(o) - f32::from(b)) * opacity).round())
    };
    Color32::from_rgba_unmultiplied(
        mix(base.r(), on.r()),
        mix(base.g(), on.g()),
        mix(base.b(), on.b()),
        base.a(),
    )
}

/// M3 state-layer opacities.
pub mod state {
    pub const HOVER: f32 = 0.08;
    pub const FOCUS: f32 = 0.10;
    pub const PRESSED: f32 = 0.10;
    pub const DRAGGED: f32 = 0.16;
    /// Disabled content is on-surface at 38%, disabled containers at 12%.
    pub const DISABLED_CONTENT: f32 = 0.38;
    pub const DISABLED_CONTAINER: f32 = 0.12;
}

// ---------------------------------------------------------------------------
// Type: the M3 type scale, as named egui TextStyles. Title M/S and the Label
// roles are weight 500; egui has no weight property, so they use a second
// face (Roboto Medium) in its own family.
// ---------------------------------------------------------------------------

pub static MEDIUM: LazyLock<FontFamily> = LazyLock::new(|| FontFamily::Name("medium".into()));
pub static ICONS: LazyLock<FontFamily> = LazyLock::new(|| FontFamily::Name("icons".into()));
pub static ICONS_FILL: LazyLock<FontFamily> =
    LazyLock::new(|| FontFamily::Name("icons-fill".into()));

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Type {
    DisplayLarge,
    DisplayMedium,
    DisplaySmall,
    HeadlineLarge,
    HeadlineMedium,
    HeadlineSmall,
    TitleLarge,
    TitleMedium,
    TitleSmall,
    BodyLarge,
    BodyMedium,
    BodySmall,
    LabelLarge,
    LabelMedium,
    LabelSmall,
}

impl Type {
    pub const ALL: [Type; 15] = [
        Type::DisplayLarge,
        Type::DisplayMedium,
        Type::DisplaySmall,
        Type::HeadlineLarge,
        Type::HeadlineMedium,
        Type::HeadlineSmall,
        Type::TitleLarge,
        Type::TitleMedium,
        Type::TitleSmall,
        Type::BodyLarge,
        Type::BodyMedium,
        Type::BodySmall,
        Type::LabelLarge,
        Type::LabelMedium,
        Type::LabelSmall,
    ];

    /// (name, size, line height, medium weight)
    pub fn spec(self) -> (&'static str, f32, f32, bool) {
        match self {
            Type::DisplayLarge => ("displayLarge", 57.0, 64.0, false),
            Type::DisplayMedium => ("displayMedium", 45.0, 52.0, false),
            Type::DisplaySmall => ("displaySmall", 36.0, 44.0, false),
            Type::HeadlineLarge => ("headlineLarge", 32.0, 40.0, false),
            Type::HeadlineMedium => ("headlineMedium", 28.0, 36.0, false),
            Type::HeadlineSmall => ("headlineSmall", 24.0, 32.0, false),
            Type::TitleLarge => ("titleLarge", 22.0, 28.0, false),
            Type::TitleMedium => ("titleMedium", 16.0, 24.0, true),
            Type::TitleSmall => ("titleSmall", 14.0, 20.0, true),
            Type::BodyLarge => ("bodyLarge", 16.0, 24.0, false),
            Type::BodyMedium => ("bodyMedium", 14.0, 20.0, false),
            Type::BodySmall => ("bodySmall", 12.0, 16.0, false),
            Type::LabelLarge => ("labelLarge", 14.0, 20.0, true),
            Type::LabelMedium => ("labelMedium", 12.0, 16.0, true),
            Type::LabelSmall => ("labelSmall", 11.0, 16.0, true),
        }
    }

    pub fn font(self) -> FontId {
        let (_, size, _, medium) = self.spec();
        FontId::new(
            size,
            if medium {
                MEDIUM.clone()
            } else {
                FontFamily::Proportional
            },
        )
    }

    pub fn style(self) -> TextStyle {
        TextStyle::Name(self.spec().0.into())
    }
}

/// Text in an M3 type role, with the role's line height.
pub fn text(s: impl Into<String>, ty: Type) -> RichText {
    RichText::new(s)
        .font(ty.font())
        .line_height(Some(ty.spec().2))
}

/// An icon glyph at `size` (M3 icons are 24).
pub fn icon(ch: char, size: f32, filled: bool) -> RichText {
    RichText::new(ch).font(FontId::new(
        size,
        if filled {
            ICONS_FILL.clone()
        } else {
            ICONS.clone()
        },
    ))
}

// ---------------------------------------------------------------------------
// Spacing, shape, size and motion tokens.
// ---------------------------------------------------------------------------

pub mod space {
    pub const XS: f32 = 4.0;
    pub const S: f32 = 8.0;
    pub const M: f32 = 12.0;
    pub const L: f32 = 16.0;
    pub const XL: f32 = 24.0;
    pub const XXL: f32 = 32.0;
}

/// M3 shape scale (corner radii).
pub mod shape {
    pub const NONE: u8 = 0;
    pub const XS: u8 = 4;
    pub const S: u8 = 8;
    pub const M: u8 = 12;
    pub const L: u8 = 16;
    pub const XL: u8 = 28;
    /// Pill: half of the tallest thing we draw (the 56px list row).
    pub const FULL: u8 = 100;
}

pub mod size {
    /// M3's minimum touch target (48dp = 48px at 160 dpi).
    pub const TOUCH: f32 = 48.0;
    pub const ICON: f32 = 24.0;
    pub const BUTTON_H: f32 = 48.0;
    pub const LIST_ROW: f32 = 56.0;
    pub const LIST_ROW_2LINE: f32 = 72.0;
    /// An icon-sized control's circular state layer (M3's 40dp), centred in
    /// its 48 px target.
    pub const STATE_LAYER_R: f32 = 20.0;
    pub const TOP_BAR: f32 = 64.0;
    /// List pane width in the list/detail layout (Compose adaptive default).
    pub const LIST_PANE: f32 = 360.0;
}

/// M3 motion durations, in seconds.
pub mod motion {
    pub const SHORT: f32 = 0.1;
    pub const MEDIUM: f32 = 0.3;
}

// ---------------------------------------------------------------------------
// Fonts.
// ---------------------------------------------------------------------------

/// Replaces egui's fonts with Roboto Regular/Medium and the Material Symbols
/// subsets (egui's `default_fonts` are off). Every family egui can ask for
/// is bound, since an unbound family panics.
pub fn install_fonts(ctx: &Context) {
    let mut defs = FontDefinitions::empty();
    let mut add = |name: &str, bytes: &'static [u8]| {
        defs.font_data
            .insert(name.to_owned(), Arc::new(FontData::from_static(bytes)));
    };
    add("roboto", include_bytes!("../assets/Roboto-Regular.ttf"));
    add(
        "roboto-medium",
        include_bytes!("../assets/Roboto-Medium.ttf"),
    );
    add(
        "icons",
        include_bytes!("../assets/MaterialSymbolsRounded-subset.ttf"),
    );
    add(
        "icons-fill",
        include_bytes!("../assets/MaterialSymbolsRounded-Fill-subset.ttf"),
    );
    let fam = |v: &[&str]| v.iter().map(|s| s.to_string()).collect::<Vec<_>>();
    // Icons are a fallback in the text families too, so an icon char inside
    // a label renders instead of tofu. They never shadow a Roboto glyph:
    // Material Symbols only covers private-use codepoints.
    defs.families
        .insert(FontFamily::Proportional, fam(&["roboto", "icons"]));
    defs.families
        .insert(FontFamily::Monospace, fam(&["roboto", "icons"]));
    defs.families
        .insert(MEDIUM.clone(), fam(&["roboto-medium", "icons"]));
    defs.families
        .insert(ICONS.clone(), fam(&["icons", "roboto"]));
    defs.families
        .insert(ICONS_FILL.clone(), fam(&["icons-fill", "roboto"]));
    ctx.set_fonts(defs);
}

// ---------------------------------------------------------------------------
// Tokens -> egui Style.
// ---------------------------------------------------------------------------

/// How text is made legible in each theme (compared on the frame with the
/// gallery's Probe page; `Shader` won). egui's default gives dark and light
/// different atlas curves, so switching rebuilds the font atlas. The other
/// modes keep one atlas for both themes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TextMode {
    /// egui's defaults: dark `2c - c^2`, light raw coverage.
    EguiDefault,
    /// Raw coverage in both themes, no correction anywhere.
    Off,
    /// Raw coverage in the atlas, `2c - c^2` applied in our fragment shader
    /// to light-coloured text only (the painter's job).
    Shader,
    /// egui's dark-mode curve in both themes: one atlas, no shader cost,
    /// dark-on-light text a little heavier.
    Boost,
}

impl TextMode {
    pub fn name(self) -> &'static str {
        match self {
            TextMode::EguiDefault => "egui",
            TextMode::Off => "off",
            TextMode::Shader => "shader",
            TextMode::Boost => "boost",
        }
    }

    fn transfer(self, theme: Theme) -> FontColorTransferFunction {
        match (self, theme) {
            (TextMode::EguiDefault, Theme::Dark) => FontColorTransferFunction::DARK_MODE_DEFAULT,
            (TextMode::EguiDefault, Theme::Light) => FontColorTransferFunction::LIGHT_MODE_DEFAULT,
            (TextMode::Boost, _) => FontColorTransferFunction::TwoCoverageMinusCoverageSq,
            (TextMode::Off | TextMode::Shader, _) => FontColorTransferFunction::Off,
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub struct Options {
    pub text_mode: TextMode,
    pub subpixel_binning: bool,
}

impl Default for Options {
    /// Chosen on the frame: the shader boost (one atlas for both themes)
    /// with sub-pixel glyph binning.
    fn default() -> Self {
        Self {
            text_mode: TextMode::Shader,
            subpixel_binning: true,
        }
    }
}

/// Registers both themes' styles and the schemes. Call once at start, and
/// again only when `Options` change; switching theme is `ctx.set_theme`.
pub fn install(ctx: &Context, schemes: Schemes, opts: Options) {
    ctx.data_mut(|d| d.insert_temp(schemes_id(), schemes));
    // A tap commits on release however long the finger stays down, as on
    // Android (UX.md, Jakob's Law); only moving past `max_click_dist` (a
    // scroll) cancels it. egui's default 0.8 s `max_click_duration` makes
    // a longer press no click at all (`could_any_button_be_click`), and on
    // touch it turns the press into a long-touch (secondary click) at 0.8 s
    // and drops the press state. The kit has no long-press actions, so no
    // limit: every control (segments, chips, buttons, rows, switches) then
    // keeps its press state while held and acts on lift.
    ctx.options_mut(|o| o.input_options.max_click_duration = f64::INFINITY);
    for theme in [Theme::Dark, Theme::Light] {
        ctx.set_style_of(theme, style(schemes.get(theme), opts, theme));
    }
}

pub fn style(s: &Scheme, opts: Options, theme: Theme) -> Style {
    let mut style = Style::default();

    style.text_styles = [
        (TextStyle::Small, Type::BodySmall.font()),
        (TextStyle::Body, Type::BodyLarge.font()),
        (
            TextStyle::Monospace,
            FontId::new(14.0, FontFamily::Monospace),
        ),
        (TextStyle::Button, Type::LabelLarge.font()),
        (TextStyle::Heading, Type::TitleLarge.font()),
    ]
    .into_iter()
    .chain(Type::ALL.iter().map(|t| (t.style(), t.font())))
    .collect();

    let sp = &mut style.spacing;
    // 12 between controls in a row, so a focus ring (5 px outside its
    // control) keeps 4 px of air to the next one (UX.md, Fitts's Law).
    sp.item_spacing = vec2(space::M, space::S);
    sp.window_margin = Margin::same(space::XL as i8);
    sp.menu_margin = Margin::same(space::S as i8);
    sp.button_padding = vec2(space::XL, space::M);
    sp.indent = space::XL;
    // Everything clickable is at least a touch target tall.
    sp.interact_size = vec2(size::TOUCH, size::TOUCH);
    sp.slider_width = 320.0;
    sp.slider_rail_height = 4.0;
    sp.combo_width = 240.0;
    sp.text_edit_width = 400.0;
    sp.icon_width = 20.0;
    sp.icon_width_inner = 12.0;
    sp.icon_spacing = space::M;
    sp.combo_height = 400.0;
    sp.menu_width = 320.0;
    sp.scroll.bar_width = 6.0;
    // egui fades 20 px at a scroll area's edges by default (50%), which made
    // a section header at the fold look disabled. M3 lists clip hard, and
    // the fade is one more blended layer.
    sp.scroll.fade.strength = 0.0;

    let ia = &mut style.interaction;
    // A finger is not a cursor: snap to a widget within this many points.
    ia.interact_radius = space::S;
    // Labels must not swallow the drag that scrolls a list.
    ia.selectable_labels = false;
    ia.multi_widget_text_select = false;

    style.animation_time = motion::SHORT;

    let v = &mut style.visuals;
    v.dark_mode = s.dark;
    v.text_options = TextOptions {
        color_transfer_function: opts.text_mode.transfer(theme),
        subpixel_binning: opts.subpixel_binning,
        ..Default::default()
    };
    v.override_text_color = None;
    v.weak_text_color = Some(s.on_surface_variant);
    v.hyperlink_color = s.primary;
    v.faint_bg_color = s.surface_container_low;
    v.extreme_bg_color = s.surface_container_highest;
    v.text_edit_bg_color = Some(s.surface_container_highest);
    v.code_bg_color = s.surface_container_high;
    v.warn_fg_color = s.warning;
    v.error_fg_color = s.error;
    v.window_corner_radius = CornerRadius::same(shape::XL);
    let shadow_alpha = if s.dark { 90 } else { 40 };
    v.window_shadow = Shadow {
        offset: [0, 4],
        blur: 16,
        spread: 0,
        color: Color32::from_black_alpha(shadow_alpha),
    };
    v.window_fill = s.surface_container_high;
    v.window_stroke = Stroke::NONE;
    v.menu_corner_radius = CornerRadius::same(shape::XS);
    v.panel_fill = s.surface;
    v.popup_shadow = Shadow {
        offset: [0, 2],
        blur: 8,
        spread: 0,
        color: Color32::from_black_alpha(shadow_alpha),
    };
    v.text_cursor = TextCursorStyle {
        stroke: Stroke::new(2.0, s.primary),
        ..Default::default()
    };
    v.button_frame = true;
    v.striped = false;
    v.slider_trailing_fill = true;
    v.handle_shape = HandleShape::Circle;
    v.disabled_alpha = state::DISABLED_CONTENT;
    v.collapsing_header_frame = false;
    v.indent_has_left_vline = false;
    // Selected buttons, text selection and the slider's filled track.
    v.selection = Selection {
        bg_fill: s.primary_container,
        stroke: Stroke::new(2.0, s.on_primary_container),
    };

    // egui's generic widgets (checkbox, radio, slider, text edit, combo,
    // plain Button) take these. `weak_bg_fill` is a button's container:
    // M3's tonal button. `bg_fill` is a checkbox box / slider rail / radio.
    let corner = CornerRadius::same(shape::S);
    let wv = |weak: Color32, bg: Color32, stroke: Stroke, fg: Color32| WidgetVisuals {
        bg_fill: bg,
        weak_bg_fill: weak,
        bg_stroke: stroke,
        corner_radius: corner,
        fg_stroke: Stroke::new(2.0, fg),
        expansion: 0.0,
    };
    let tonal = s.secondary_container;
    let on_tonal = s.on_secondary_container;
    let well = s.surface_container_highest;
    v.widgets = Widgets {
        noninteractive: wv(
            s.surface_container,
            s.surface_container,
            Stroke::new(1.0, s.outline_variant),
            s.on_surface,
        ),
        inactive: wv(tonal, well, Stroke::NONE, on_tonal),
        hovered: wv(
            layer(tonal, on_tonal, state::HOVER),
            layer(well, s.on_surface, state::HOVER),
            Stroke::NONE,
            on_tonal,
        ),
        active: wv(
            layer(tonal, on_tonal, state::PRESSED),
            layer(well, s.on_surface, state::PRESSED),
            Stroke::new(2.0, s.primary),
            on_tonal,
        ),
        open: wv(
            layer(tonal, on_tonal, state::FOCUS),
            layer(well, s.on_surface, state::FOCUS),
            Stroke::NONE,
            on_tonal,
        ),
    };
    style
}
