#!/bin/sh
# Rebuilds the Material Symbols subsets from Google's variable font,
# keeping only the icons named in crates/raam-core/assets/icons.txt, and
# regenerates crates/raam-core/src/icons.rs to match. Needs curl and uv
# (fonttools runs through uvx; nothing is installed globally).
#   -subset.ttf       static, FILL=0 wght=400 GRAD=0 opsz=24 (the default)
#   -Fill-subset.ttf  static, FILL=1 (selected states)
set -eu
here=$(cd "$(dirname "$0")/.." && pwd)
assets="$here/crates/raam-core/assets"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
base='https://raw.githubusercontent.com/google/material-design-icons/master/variablefont'
name='MaterialSymbolsRounded%5BFILL,GRAD,opsz,wght%5D'
curl -sSfL -o "$work/full.ttf" "$base/$name.ttf"
curl -sSfL -o "$work/full.codepoints" "$base/$name.codepoints"
unicodes=$(while read -r icon; do
    cp=$(awk -v n="$icon" '$1 == n { print $2; exit }' "$work/full.codepoints")
    [ -n "$cp" ] || { echo "no codepoint for $icon" >&2; exit 1; }
    printf 'U+%s,' "$(echo "$cp" | tr a-f A-F)"
done < "$assets/icons.txt")
unicodes=${unicodes%,}
ft() { uvx --from fonttools "$@"; }
ft fonttools varLib.instancer "$work/full.ttf" FILL=0 wght=400 GRAD=0 opsz=24 -q -o "$work/st0.ttf"
ft fonttools varLib.instancer "$work/full.ttf" FILL=1 wght=400 GRAD=0 opsz=24 -q -o "$work/st1.ttf"
sub() {
    ft pyftsubset "$work/$1.ttf" --unicodes="$unicodes" --layout-features='' \
        --no-hinting --desubroutinize --output-file="$assets/$2"
}
sub st0 MaterialSymbolsRounded-subset.ttf
sub st1 MaterialSymbolsRounded-Fill-subset.ttf
# Keep src/icons.rs in step with icons.txt.
{
    echo '//! Material Symbols Rounded codepoints for the icons in assets/icons.txt.'
    echo '//! Generated by tools/build-icons.sh; do not edit by hand.'
    while read -r icon; do
        cp=$(awk -v n="$icon" '$1 == n { print $2; exit }' "$work/full.codepoints")
        printf "pub const %s: char = '\\\\u{%s}';\n" "$(echo "$icon" | tr a-z A-Z)" "$cp"
    done < "$assets/icons.txt"
    echo
    echo '/// Every icon above with its name, for the gallery.'
    echo 'pub const ALL: &[(&str, char)] = &['
    while read -r icon; do
        printf '    ("%s", %s),\n' "$icon" "$(echo "$icon" | tr a-z A-Z)"
    done < "$assets/icons.txt"
    echo '];'
} > "$here/crates/raam-core/src/icons.rs"
echo "icons: $(wc -l < "$assets/icons.txt") -> $(ls -l "$assets/"MaterialSymbolsRounded-*.ttf | awk '{s = s " " $5} END {print s}') bytes"
